spring.application.name=stranger-api-rest

# ==========================
# DATASOURCE
# ==========================

spring.datasource.url=jdbc:postgresql://ep-shiny-dew-aqtf3060-pooler.c-8.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
spring.datasource.password=npg_FXjTVg9M3AdN
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=neondb_owner

# ==========================
# JPA
# ==========================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
