spring.application.name=stranger-api-rest

# ==========================
# DATASOURCE
# ==========================

spring.datasource.url=jdbc:postgresql://dpg-d86vbsrbc2fs73bf9oog-a.oregon-postgres.render.com/database_stranger?sslmode=require
spring.datasource.password=g3YxCBBf7a9d2KGNMNQy1eJZXM6HIy3Q
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=database_stranger_user

# ==========================
# JPA
# ==========================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
